// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/messagedata.proto

package models;

public final class Messagedata {
  private Messagedata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:models.MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required string Command = 1;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>required string Command = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();

    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getCommandArgumentsList();
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    int getCommandArgumentsCount();
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    java.lang.String getCommandArguments(int index);
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommandArgumentsBytes(int index);

    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getStormArgumentsList();
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    int getStormArgumentsCount();
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    java.lang.String getStormArguments(int index);
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    com.google.protobuf.ByteString
        getStormArgumentsBytes(int index);

    /**
     * <code>optional bytes Payload = 4;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional bytes Payload = 4;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code models.MessageData}
   */
  public static final class MessageData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:models.MessageData)
      MessageDataOrBuilder {
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageData defaultInstance;
    public static MessageData getDefaultInstance() {
      return defaultInstance;
    }

    public MessageData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              command_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                commandArguments_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              commandArguments_.add(bs);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                stormArguments_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              stormArguments_.add(bs);
              break;
            }
            case 34: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          commandArguments_ = commandArguments_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          stormArguments_ = stormArguments_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return models.Messagedata.internal_static_models_MessageData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return models.Messagedata.internal_static_models_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              models.Messagedata.MessageData.class, models.Messagedata.MessageData.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageData> PARSER =
        new com.google.protobuf.AbstractParser<MessageData>() {
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private java.lang.Object command_;
    /**
     * <code>required string Command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Command = 1;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Command = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMANDARGUMENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList commandArguments_;
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCommandArgumentsList() {
      return commandArguments_;
    }
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    public int getCommandArgumentsCount() {
      return commandArguments_.size();
    }
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    public java.lang.String getCommandArguments(int index) {
      return commandArguments_.get(index);
    }
    /**
     * <code>repeated string CommandArguments = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommandArgumentsBytes(int index) {
      return commandArguments_.getByteString(index);
    }

    public static final int STORMARGUMENTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stormArguments_;
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStormArgumentsList() {
      return stormArguments_;
    }
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    public int getStormArgumentsCount() {
      return stormArguments_.size();
    }
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    public java.lang.String getStormArguments(int index) {
      return stormArguments_.get(index);
    }
    /**
     * <code>repeated string StormArguments = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStormArgumentsBytes(int index) {
      return stormArguments_.getByteString(index);
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes Payload = 4;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes Payload = 4;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private void initFields() {
      command_ = "";
      commandArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      stormArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCommandBytes());
      }
      for (int i = 0; i < commandArguments_.size(); i++) {
        output.writeBytes(2, commandArguments_.getByteString(i));
      }
      for (int i = 0; i < stormArguments_.size(); i++) {
        output.writeBytes(3, stormArguments_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(4, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCommandBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commandArguments_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(commandArguments_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCommandArgumentsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stormArguments_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stormArguments_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStormArgumentsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static models.Messagedata.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.Messagedata.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.Messagedata.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.Messagedata.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.Messagedata.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static models.Messagedata.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static models.Messagedata.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static models.Messagedata.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static models.Messagedata.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static models.Messagedata.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(models.Messagedata.MessageData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code models.MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:models.MessageData)
        models.Messagedata.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return models.Messagedata.internal_static_models_MessageData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return models.Messagedata.internal_static_models_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                models.Messagedata.MessageData.class, models.Messagedata.MessageData.Builder.class);
      }

      // Construct using models.Messagedata.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        commandArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        stormArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return models.Messagedata.internal_static_models_MessageData_descriptor;
      }

      public models.Messagedata.MessageData getDefaultInstanceForType() {
        return models.Messagedata.MessageData.getDefaultInstance();
      }

      public models.Messagedata.MessageData build() {
        models.Messagedata.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public models.Messagedata.MessageData buildPartial() {
        models.Messagedata.MessageData result = new models.Messagedata.MessageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          commandArguments_ = commandArguments_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.commandArguments_ = commandArguments_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stormArguments_ = stormArguments_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stormArguments_ = stormArguments_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof models.Messagedata.MessageData) {
          return mergeFrom((models.Messagedata.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(models.Messagedata.MessageData other) {
        if (other == models.Messagedata.MessageData.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          bitField0_ |= 0x00000001;
          command_ = other.command_;
          onChanged();
        }
        if (!other.commandArguments_.isEmpty()) {
          if (commandArguments_.isEmpty()) {
            commandArguments_ = other.commandArguments_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCommandArgumentsIsMutable();
            commandArguments_.addAll(other.commandArguments_);
          }
          onChanged();
        }
        if (!other.stormArguments_.isEmpty()) {
          if (stormArguments_.isEmpty()) {
            stormArguments_ = other.stormArguments_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStormArgumentsIsMutable();
            stormArguments_.addAll(other.stormArguments_);
          }
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        models.Messagedata.MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (models.Messagedata.MessageData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object command_ = "";
      /**
       * <code>required string Command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Command = 1;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            command_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Command = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Command = 1;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string Command = 1;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList commandArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCommandArgumentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          commandArguments_ = new com.google.protobuf.LazyStringArrayList(commandArguments_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCommandArgumentsList() {
        return commandArguments_.getUnmodifiableView();
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public int getCommandArgumentsCount() {
        return commandArguments_.size();
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public java.lang.String getCommandArguments(int index) {
        return commandArguments_.get(index);
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommandArgumentsBytes(int index) {
        return commandArguments_.getByteString(index);
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public Builder setCommandArguments(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCommandArgumentsIsMutable();
        commandArguments_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public Builder addCommandArguments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCommandArgumentsIsMutable();
        commandArguments_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public Builder addAllCommandArguments(
          java.lang.Iterable<java.lang.String> values) {
        ensureCommandArgumentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commandArguments_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public Builder clearCommandArguments() {
        commandArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string CommandArguments = 2;</code>
       */
      public Builder addCommandArgumentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCommandArgumentsIsMutable();
        commandArguments_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stormArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStormArgumentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stormArguments_ = new com.google.protobuf.LazyStringArrayList(stormArguments_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStormArgumentsList() {
        return stormArguments_.getUnmodifiableView();
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public int getStormArgumentsCount() {
        return stormArguments_.size();
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public java.lang.String getStormArguments(int index) {
        return stormArguments_.get(index);
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStormArgumentsBytes(int index) {
        return stormArguments_.getByteString(index);
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public Builder setStormArguments(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStormArgumentsIsMutable();
        stormArguments_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public Builder addStormArguments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStormArgumentsIsMutable();
        stormArguments_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public Builder addAllStormArguments(
          java.lang.Iterable<java.lang.String> values) {
        ensureStormArgumentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stormArguments_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public Builder clearStormArguments() {
        stormArguments_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StormArguments = 3;</code>
       */
      public Builder addStormArgumentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStormArgumentsIsMutable();
        stormArguments_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Payload = 4;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes Payload = 4;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes Payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Payload = 4;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:models.MessageData)
    }

    static {
      defaultInstance = new MessageData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:models.MessageData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_MessageData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_models_MessageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!google/protobuf/messagedata.proto\022\006mod" +
      "els\"a\n\013MessageData\022\017\n\007Command\030\001 \002(\t\022\030\n\020C" +
      "ommandArguments\030\002 \003(\t\022\026\n\016StormArguments\030" +
      "\003 \003(\t\022\017\n\007Payload\030\004 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_models_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_models_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_models_MessageData_descriptor,
        new java.lang.String[] { "Command", "CommandArguments", "StormArguments", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
